//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventBookingPlatform.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevEventBookingDBEntities : DbContext
    {
        public DevEventBookingDBEntities()
            : base("name=DevEventBookingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Catering> Caterings { get; set; }
        public virtual DbSet<CateringValue> CateringValues { get; set; }
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<ChefSpokenLanguage> ChefSpokenLanguages { get; set; }
        public virtual DbSet<ChildrenOption> ChildrenOptions { get; set; }
        public virtual DbSet<ChildrenOptionComment> ChildrenOptionComments { get; set; }
        public virtual DbSet<ChildrenOptionValue> ChildrenOptionValues { get; set; }
        public virtual DbSet<DisabledOption> DisabledOptions { get; set; }
        public virtual DbSet<DisabledOptionComment> DisabledOptionComments { get; set; }
        public virtual DbSet<DisabledOptionValue> DisabledOptionValues { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FacilityOption> FacilityOptions { get; set; }
        public virtual DbSet<FacilityOptionValue> FacilityOptionValues { get; set; }
        public virtual DbSet<Hall> Halls { get; set; }
        public virtual DbSet<Kitchen> Kitchens { get; set; }
        public virtual DbSet<KitchenValue> KitchenValues { get; set; }
        public virtual DbSet<KosherSupervision> KosherSupervisions { get; set; }
        public virtual DbSet<KosherSupervisionComment> KosherSupervisionComments { get; set; }
        public virtual DbSet<KosherSuperVisionValue> KosherSuperVisionValues { get; set; }
        public virtual DbSet<ParkingOption> ParkingOptions { get; set; }
        public virtual DbSet<ParkingOptionComment> ParkingOptionComments { get; set; }
        public virtual DbSet<ParkingOptionValue> ParkingOptionValues { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<VenueChildrenOption> VenueChildrenOptions { get; set; }
        public virtual DbSet<VenueContact> VenueContacts { get; set; }
        public virtual DbSet<VenueDescription> VenueDescriptions { get; set; }
        public virtual DbSet<VenueDisabledOption> VenueDisabledOptions { get; set; }
        public virtual DbSet<VenueFacility> VenueFacilities { get; set; }
        public virtual DbSet<VenueParkingOption> VenueParkingOptions { get; set; }
        public virtual DbSet<VenueWaitingRoomOption> VenueWaitingRoomOptions { get; set; }
        public virtual DbSet<WaitingRoomOption> WaitingRoomOptions { get; set; }
        public virtual DbSet<WaitingRoomOptionComment> WaitingRoomOptionComments { get; set; }
        public virtual DbSet<WaitingRoomOptionValue> WaitingRoomOptionValues { get; set; }
        public virtual DbSet<PrivateEvent> PrivateEvents { get; set; }
        public virtual DbSet<VenueEvent> VenueEvents { get; set; }
        public virtual DbSet<VenueType> VenueTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<BusinessEvent> BusinessEvents { get; set; }
        public virtual DbSet<VenueCertificate> VenueCertificates { get; set; }
        public virtual DbSet<VenueInfo> VenueInfoes { get; set; }
        public virtual DbSet<VenueCharacterization> VenueCharacterizations { get; set; }
        public virtual DbSet<VenueActivityTime> VenueActivityTimes { get; set; }
    }
}
