//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventBookingPlatform.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Pk_EquipSupplierId { get; set; }
        public string OutsideSupplier { get; set; }
        public string PaSupplier { get; set; }
        public string StageLighting { get; set; }
        public string DessertsBar { get; set; }
        public string LiquorBarSupplier { get; set; }
        public string SecurityCheckSupplier { get; set; }
    }
}
