//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventBookingPlatform.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueCharacterization
    {
        public int Pk_VenueCharId { get; set; }
        public int Fk_VenueId { get; set; }
        public string TypeOfConstruction { get; set; }
        public string OpenAreas { get; set; }
        public string AView { get; set; }
        public string MaxNoRoomsAreas { get; set; }
        public string Parking { get; set; }
        public string Privacy { get; set; }
        public string PagesIn { get; set; }
    
        public virtual VenueInfo VenueInfo { get; set; }
    }
}
